version: "3"

services:

  api:
    container_name: PatentKeeper
    image: patentkeeper
    build: ./website
    restart: always
    volumes:
      - ./website/:/docker/PatentKeeper
    ports:
      - 8082:8082